# docker-compose.yml
version: '3.8'

services:
  web-client:
    build: ./web-client
    depends_on:
      - api-server
      - ws-server
    networks:
      - chat-network

  api-server:
    build: ./api-server
    ports:
      - "5001:5001"
    env_file:
      - ./api-server/.env
    networks:
      - chat-network

  ws-server:
    build: ./ws-server
    ports:
      - "8000:8000"
    env_file:
      - ./ws-server/.env
    networks:
      - chat-network
        
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-client
      - api-server
      - ws-server
    networks:
      - chat-network
      
networks:
  chat-network:
    driver: bridge
